package system;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    Organization - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class OrganizationTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Organization";
    public static final String TABLE = "Organization";
    private static final String DESCRIPTION = "All organizations";

    public enum Columns {Name, Date, Description, Config, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new DateColumn("Date", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
    };

    private static final Organization associatedObject = new Organization();
    public OrganizationTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public OrganizationTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {

          {"no org", "2014-01-01", "Generic", "system"},
          {"itClarifies", "2014-01-01", "Our own group", "system"},



    };
    private static final String[][] TestValues = {

          {"demo.org", "2014-01-02", "Test organization in the system", "system"},
          {"evil.org", "2014-01-03", "Another organization that should not see the documents", "system"},



    };

    @Override
    public void clearConstantCache(){

        Organization.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
