package system;

import system.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    Organization - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class OrganizationTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Organization";
    public static final String TABLE = "Organization";
    private static final String DESCRIPTION = "All organizations";

    public enum Columns {Name, Users, Date, Link, Description, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new IntColumn("Users", DataColumn.noFormatting),
            new DateColumn("Date", DataColumn.noFormatting),
            new TextColumn("Link", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
    };

    private static final Organization associatedObject = new Organization();
    public OrganizationTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public OrganizationTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {

          {"no org", "0", "2014-01-01", "http://localhost:8080", "Generic", "system"},
          {"itClarifies", "2", "2014-01-01", "http://localhost:8080", "Our own group", "system"},



    };
    private static final String[][] TestValues = {

          {"demo.org", "3", "2014-01-02", "http://localhost:8080", "Test organization in the system", "system"},
          {"evil.org", "1", "2014-01-03", "http://localhost:8080", "Another organization that should not see the documents", "system"},



    };

    @Override
    public void clearConstantCache(){

        Organization.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
