package system;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    PortalSession - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class PortalSessionTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Session";
    public static final String TABLE = "PortalSession";
    private static final String DESCRIPTION = "Active and closed sessions for all users";

    public enum Columns {User, Token, Start, Latest, Status, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new ReferenceColumn("User", DataColumn.noFormatting, new TableReference("PortalUser", "Name")),
            new StringColumn("Token", DataColumn.noFormatting),
            new TimeStampColumn("Start", DataColumn.noFormatting),
            new TimeStampColumn("Latest", DataColumn.noFormatting),
            new ReferenceColumn("Status", DataColumn.noFormatting, new TableReference("SessionStatus", "Name")),
    };

    private static final PortalSession associatedObject = new PortalSession();
    public PortalSessionTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
        nameColumn = 2;
        // Not set as external
        // Not a constant table
    }

    public PortalSessionTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {

          {"System", "SystemSessionToken", "2020-05-01 00:00:00", "2015-05-01 00:00:00", "open", "system"},



    };
    private static final String[][] TestValues = {

          {"demo", "DummySessionToken", "2015-05-01 00:00:00", "2015-05-01 00:00:00", "open", "system"},
          {"admin", "DummyAdminToken", "2015-05-01 00:00:00", "2015-05-01 00:00:00", "open", "system"},
          {"eve", "DummyEveToken", "2015-05-01 00:00:00", "2015-05-01 00:00:00", "open", "system"},



    };

    @Override
    public void clearConstantCache(){

        PortalSession.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/




    /*************************************************************************************
     *
     *          Create a new session given username and password
     *
     * @param user - the user as entered in the login
     * @return - a new session
     * @throws BackOfficeException
     */


    public PortalSession createNewSession(PortalUser user) throws BackOfficeException {


        SessionToken token = new SessionToken();
        DBTimeStamp startTime = new DBTimeStamp();  // Now
        SessionStatus status;

        status = SessionStatus.getopen();
        PortalSession session = new PortalSession(user, token.toString(), startTime.getSQLTime().toString(), startTime.getSQLTime().toString(), status);
        session.store();
        return session;


    }

}
